apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-event-reporter
  namespace: eirini-core
spec:
  selector:
    matchLabels:
      name: eirini-event-reporter
  template:
    metadata:
      labels:
        name: eirini-event-reporter
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-event-reporter
      volumes:
        - name: config-map-volume
          configMap:
            name: eirini-event-reporter
        - name: cc-certs
          secret:
            secretName: capi-tls
            optional: true
      securityContext:
        runAsNonRoot: true
      containers:
      - name: event-reporter
        image: eirini/event-reporter@sha256:3126f18d70c2dc091f5ab77d2ecea61c0e145061adb8c22b3b4c7e8b9a913f00
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini-event-reporter/config
        - name: cc-certs
          mountPath: /etc/cf-api/certs
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 100m
            memory: 100Mi
