apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-event-reporter
  namespace: eirini-core
spec:
  selector:
    matchLabels:
      name: eirini-event-reporter
  replicas: 2
  template:
    metadata:
      labels:
        name: eirini-event-reporter
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-event-reporter
      volumes:
        - name: config-map-volume
          configMap:
            name: eirini-event-reporter
        - name: cc-certs
          secret:
            secretName: capi-tls
            optional: true
      securityContext:
        runAsNonRoot: true
      containers:
      - name: event-reporter
        image: eirini/event-reporter@sha256:32541544872dc17379638b9867e230cabf10b2629dff8cf1b0c7d097948db79b
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini-event-reporter/config
        - name: cc-certs
          mountPath: /etc/cf-api/certs
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 100m
            memory: 100Mi
