---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eirini-task-reporter
  namespace: eirini-core
spec:
  selector:
    matchLabels:
      name: eirini-task-reporter
  template:
    metadata:
      labels:
        name: eirini-task-reporter
    spec:
      dnsPolicy: ClusterFirst
      serviceAccountName: eirini-task-reporter
      securityContext:
        runAsNonRoot: true
      containers:
      - name: task-reporter
        image: eirini/task-reporter@sha256:3a649b9359960dbc94d2825e33535dc616e423ef4800878a446dabb175d9fd9a
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config-map-volume
          mountPath: /etc/eirini/config
        - name: cc-certs
          mountPath: /etc/cf-api/certs
      volumes:
        - name: config-map-volume
          configMap:
            name: task-reporter
            items:
            - key: task-reporter.yml
              path: task-reporter.yml
        - name: cc-certs
          secret:
            secretName: eirini-certs
            optional: true
