bits:
  kube:
    external_ips:
    - 1.2.3.4
  secrets:
    BITS_TLS_CRT: certificate
    BITS_TLS_KEY: key
eirini:
  kube:
    external_ips:
    - 1.2.3.4
  opi:
    ingress_endpoint: ingress.end.point
    use_registry_ingress: true
  secrets:
    BITS_SERVICE_SECRET: aK$GiuqqL9lpXrQE8o@X%'"
    BITS_SERVICE_SIGNING_USER_PASSWORD: aK$GiuqqL9lpXrQE8o@X%'"
    BLOBSTORE_PASSWORD: aK$GiuqqL9lpXrQE8o@X%'"
  services:
    loadbalanced: false
env:
  DOMAIN: cool.nice.io
  UAA_HOST: uaa.cool.nice.io
  UAA_PORT: 2793
kube:
  auth: rbac
  external_ips:
  - 1.2.3.4
  storage_class:
    persistent: hostpath
    shared: hostpath
secrets:
  BLOBSTORE_PASSWORD: aK$GiuqqL9lpXrQE8o@X%'"
  CLUSTER_ADMIN_PASSWORD: aK$GiuqqL9lpXrQE8o@X%'"
  UAA_ADMIN_CLIENT_SECRET: aK$GiuqqL9lpXrQE8o@X%'"
services:
  loadbalanced: false
