opi:
  # set ingress endoint when 'use_registry_ingress' is set to true
  ingress_endpoint: no-ingress-set
  use_registry_ingress: false
  use_docker: false

  namespace: eirini
  version: 0.0.0
  init_image: eirini/opi-init
  image: eirini/opi
  image_tag: latest
  rootfs_version: 24.0.0
  rootfs_patcher_timeout: -1ns
  stager:
    downloader_image: eirini/recipe-downloader
    downloader_image_tag: sha256:7b16e8b2aa675027a6d3b9bfb39c1cce70541e4d2bfe0e416db50fcab6da97bd
    executor_image: eirini/recipe-executor
    executor_image_tag: sha256:707fb68723402347344364c4334dd822ba7247ba660cfebe6cbe1edbba7c3f9e
    uploader_image: eirini/recipe-uploader
    uploader_image_tag: sha256:a7ab8fabc6024a73a774ee42c14d4eaceda0fc4528471098a906ab36889dba70
kube:
  external_ips: []

scf:
  version: 2.14.5
  secrets_generation_counter: 1

services:
  loadbalanced: false

secrets:
  BITS_SERVICE_SECRET: secret
  BITS_SERVICE_SIGNING_USER_PASSWORD: notpassword123
  BLOBSTORE_PASSWORD:  blobstore

env:
  # Base domain of the SCF cluster.
  # Example: "my-scf-cluster.com"
  DOMAIN: ~

