opi:
  # set ingress endoint when 'use_registry_ingress' is set to true
  ingress_endpoint: no-ingress-set
  use_registry_ingress: false

  namespace: eirini
  version: 0.0.0
  stager_image: eirini/recipe:latest

kube:
  external_ips: []

scf:
  version: 2.14.5
  secrets_generation_counter: 1

services:
  loadbalanced: false

secrets:
  BITS_SERVICE_SECRET: secret
  BITS_SERVICE_SIGNING_USER_PASSWORD: notpassword123
  BLOBSTORE_PASSWORD:  blobstore

env:
  # Base domain of the SCF cluster.
  # Example: "my-scf-cluster.com"
  DOMAIN: ~
