opi:
  # set ingress endoint when 'use_registry_ingress' is set to true
  ingress_endpoint: no-ingress-set
  use_registry_ingress: false
  use_docker: false

  namespace: eirini
  version: 0.0.0
  image_tag: latest
  init_image: eirini/opi-init:latest
  image: eirini/opi:latest
  stager:
    downloader_image: eirini/recipe-downloader:latest
    uploader_image: eirini/recipe-uploader:latest
    executor_image: eirini/recipe-executor:latest

kube:
  external_ips: []

scf:
  version: 2.14.5
  secrets_generation_counter: 1

services:
  loadbalanced: false

secrets:
  BITS_SERVICE_SECRET: secret
  BITS_SERVICE_SIGNING_USER_PASSWORD: notpassword123
  BLOBSTORE_PASSWORD:  blobstore

env:
  # Base domain of the SCF cluster.
  # Example: "my-scf-cluster.com"
  DOMAIN: ~
