opi:
  image_tag: latest

  # set ingress endoint when 'use_registry_ingress' is set to true
  ingress_endpoint: no-ingress-set
  use_registry_ingress: false

  namespace: eirini
  version: 0.0.0
  image_tag: latest

bits:

kube:
  external_ips:
  - 1.2.3.4

scf:
  version: 2.14.5
  secrets_generation_counter: 1

secrets:
  BITS_SERVICE_SECRET: secret
  BITS_SERVICE_SIGNING_USER_PASSWORD: notpassword123
  BLOBSTORE_PASSWORD:  blobstore
