cubefs/cubefs.tar:
  size: 922284032
  sha: db2f3ace39b49c2afe36594222a64d018daaa215
golang/go1.9.2.linux-amd64.tar.gz:
  size: 104247844
  object_id: 2f9de529-3ef3-49d2-4089-088c567b46c9
  sha: 94c889e039e3d2e94ed95e8f8cb747c5bc1c2b58
