---
# Service account "default-privileged" is used by the following instance groups:
# - api-group
# - autoscaler-api
# - autoscaler-servicebroker
# - blobstore
# - cf-usb-group
# - credhub-user
# - log-api
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "default-privileged"
  labels:
    app.kubernetes.io/component: "default-privileged"
    skiff-role-name: "default-privileged"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
{{- end }}
---
# Role binding for service account "default-privileged" and role
# "configgin-role"
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "default-privileged-configgin-role-binding"
  labels:
    app.kubernetes.io/component: "default-privileged-configgin-role-binding"
    skiff-role-name: "default-privileged-configgin-role-binding"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
subjects:
- kind: "ServiceAccount"
  name: "default-privileged"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "configgin-role"
{{- end }}
---
# Cluster role binding for service account "default-privileged" and cluster role
# "nonprivileged"
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: {{ template "fissile.SanitizeName" (printf "%s-default-privileged-nonprivileged-cluster-binding" .Release.Namespace) }}
  labels:
    app.kubernetes.io/component: {{ template "fissile.SanitizeName" (printf "%s-default-privileged-nonprivileged-cluster-binding" .Release.Namespace) }}
    skiff-role-name: {{ template "fissile.SanitizeName" (printf "%s-default-privileged-nonprivileged-cluster-binding" .Release.Namespace) }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
subjects:
- kind: "ServiceAccount"
  name: "default-privileged"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: {{ template "fissile.SanitizeName" (printf "%s-cluster-role-nonprivileged" .Release.Namespace) }}
{{- end }}
---
# Cluster role binding for service account "default-privileged" and cluster role
# "privileged"
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: {{ template "fissile.SanitizeName" (printf "%s-default-privileged-privileged-cluster-binding" .Release.Namespace) }}
  labels:
    app.kubernetes.io/component: {{ template "fissile.SanitizeName" (printf "%s-default-privileged-privileged-cluster-binding" .Release.Namespace) }}
    skiff-role-name: {{ template "fissile.SanitizeName" (printf "%s-default-privileged-privileged-cluster-binding" .Release.Namespace) }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
subjects:
- kind: "ServiceAccount"
  name: "default-privileged"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: {{ template "fissile.SanitizeName" (printf "%s-cluster-role-privileged" .Release.Namespace) }}
{{- end }}
