---
# Role "configgin-role" used by accounts:
# - default
# - eirini
# - garden-runc
# - secret-generator
# - tests-brain
# - tests-sits
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "configgin-role"
  labels:
    app.kubernetes.io/component: "configgin-role"
    skiff-role-name: "configgin-role"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "list"
  - "patch"
- apiGroups:
  - ""
  resources:
  - "services"
  verbs:
  - "get"
- apiGroups:
  - "apps"
  resources:
  - "statefulsets"
  verbs:
  - "get"
  - "patch"
{{- end }}
