---
# Role "psp-role" used by accounts:
# - default
# - garden-runc
# - secret-generator
# - tests-brain
# - tests-sits
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") (.Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1") }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "psp-role"
  labels:
    app.kubernetes.io/component: "psp-role"
    skiff-role-name: "psp-role"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
rules:
- apiGroups:
  - "extensions"
  resourceNames:
  - {{ if .Values.kube.psp.default }}{{ .Values.kube.psp.default }}{{ else }}{{ template "fissile.SanitizeName" (printf "%s-psp-default" .Release.Namespace) }}{{ end }}
  resources:
  - "podsecuritypolicies"
  verbs:
  - "use"
{{- end }}
