---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-postgres-set"
    labels:
      app.kubernetes.io/component: "autoscaler-postgres-set"
      skiff-role-name: "autoscaler-postgres-set"
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
      app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
      helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
      {{- if .Values.config.use_istio }}
      app: "autoscaler-postgres-set"
      {{- end }}
  spec:
    clusterIP: "None"
    ports:
    - name: "postgres"
      port: 5432
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-postgres"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-postgres-postgres-set"
    labels:
      app.kubernetes.io/component: "autoscaler-postgres-postgres-set"
      skiff-role-name: "autoscaler-postgres-postgres-set"
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
      app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
      helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
      {{- if .Values.config.use_istio }}
      app: "autoscaler-postgres-postgres-set"
      {{- end }}
  spec:
    clusterIP: "None"
    ports:
    - name: "postgres"
      port: 5432
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-postgres"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-postgres-postgres"
    labels:
      app.kubernetes.io/component: "autoscaler-postgres-postgres"
      skiff-role-name: "autoscaler-postgres-postgres"
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
      app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
      app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
      helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
      {{- if .Values.config.use_istio }}
      app: "autoscaler-postgres-postgres"
      {{- end }}
  spec:
    ports:
    - name: "postgres"
      port: 5432
      protocol: "TCP"
      targetPort: 5432
    selector:
      app.kubernetes.io/component: "autoscaler-postgres"
kind: "List"
---
# The autoscaler-postgres instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - postgres: The Postgres server provides a single instance Postgres database
#   that can be used with the Cloud Controller or the UAA. It does not provide
#   highly-available configuration.

{{- if gt (int .Values.sizing.autoscaler_postgres.count) 3 }}
_maxReplicas: {{ fail "autoscaler_postgres cannot have more than 3 instances" }}
{{- end }}

{{- if and .Values.config.HA (and (ne (int .Values.sizing.autoscaler_postgres.count) 1) (lt (int .Values.sizing.autoscaler_postgres.count) 2)) }}
_minHAReplicas: {{ fail "autoscaler_postgres must have at least 2 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.autoscaler_postgres.count) 1 }}
_minReplicas: {{ fail "autoscaler_postgres must have at least 1 instances" }}
{{- end }}

{{- if .Values.sizing.HA }}
_moved_sizing_HA: {{ fail "Bad use of moved variable sizing.HA. The new name to use is config.HA" }}
{{- end }}

{{- if .Values.sizing.cpu }}
_moved_sizing_cpu_limits: {{ if .Values.sizing.cpu.limits }} {{ fail "Bad use of moved variable sizing.cpu.limits. The new name to use is config.cpu.limits" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.cpu }}
_moved_sizing_cpu_requests: {{ if .Values.sizing.cpu.requests }} {{ fail "Bad use of moved variable sizing.cpu.requests. The new name to use is config.cpu.requests" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.memory }}
_moved_sizing_memory_limits: {{ if .Values.sizing.memory.limits }} {{ fail "Bad use of moved variable sizing.memory.limits. The new name to use is config.memory.limits" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.memory }}
_moved_sizing_memory_requests: {{ if .Values.sizing.memory.requests }} {{ fail "Bad use of moved variable sizing.memory.requests. The new name to use is config.memory.requests" }} {{else}} ok {{end}}
{{- end }}

apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-postgres"
  labels:
    app.kubernetes.io/component: "autoscaler-postgres"
    skiff-role-name: "autoscaler-postgres"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}

    {{- if .Values.config.use_istio }}
    app: "autoscaler-postgres"
    {{- end }}

    {{- if .Values.config.use_istio }}
    version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    {{- end }}

spec:
  podManagementPolicy: "Parallel"
  replicas: {{ if and .Values.config.HA (eq (int .Values.sizing.autoscaler_postgres.count) 1) -}} 2 {{- else -}} {{ .Values.sizing.autoscaler_postgres.count }} {{- end }}
  selector:
    matchLabels:
      skiff-role-name: "autoscaler-postgres"
  serviceName: "autoscaler-postgres-set"
  template:
    metadata:
      name: "autoscaler-postgres"
      labels:
        app.kubernetes.io/component: "autoscaler-postgres"
        skiff-role-name: "autoscaler-postgres"
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
        app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
        helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}

        {{- if .Values.config.use_istio }}
        app: "autoscaler-postgres"
        {{- end }}

        {{- if .Values.config.use_istio }}
        version: {{ default .Chart.Version .Chart.AppVersion | quote }}
        {{- end }}

      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.config.use_istio }}
        sidecar.istio.io/inject: "false"
        {{- end }}
    spec:
      affinity:
        {{- if .Values.sizing.autoscaler_postgres.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.autoscaler_postgres.affinity.nodeAffinity }}
        {{- end }}
      containers:
      - env:
        - name: "AUTOSCALER_DATABASE_MAX_CONNECTIONS"
          value: {{if ne (typeOf .Values.env.AUTOSCALER_DATABASE_MAX_CONNECTIONS) "<nil>"}}{{if has (kindOf .Values.env.AUTOSCALER_DATABASE_MAX_CONNECTIONS) (list "map" "slice")}}{{.Values.env.AUTOSCALER_DATABASE_MAX_CONNECTIONS | toJson | quote}}{{else}}{{.Values.env.AUTOSCALER_DATABASE_MAX_CONNECTIONS | quote}}{{end}}{{else}}""{{end}}

        {{- if not .Values.secrets.AUTOSCALER_DB_PASSWORD }}
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.AUTOSCALER_DB_PASSWORD }}
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        {{- end }}

        - name: "AZ_LABEL_NAME"
          value: {{if ne (typeOf .Values.env.AZ_LABEL_NAME) "<nil>"}}{{if has (kindOf .Values.env.AZ_LABEL_NAME) (list "map" "slice")}}{{.Values.env.AZ_LABEL_NAME | toJson | quote}}{{else}}{{.Values.env.AZ_LABEL_NAME | quote}}{{end}}{{else}}""{{end}}
        - name: "CATS_SUITES"
          value: {{if ne (typeOf .Values.env.CATS_SUITES) "<nil>"}}{{if has (kindOf .Values.env.CATS_SUITES) (list "map" "slice")}}{{.Values.env.CATS_SUITES | toJson | quote}}{{else}}{{.Values.env.CATS_SUITES | quote}}{{end}}{{else}}""{{end}}
        - name: "GARDEN_ROOTFS_DRIVER"
          value: {{if ne (typeOf .Values.env.GARDEN_ROOTFS_DRIVER) "<nil>"}}{{if has (kindOf .Values.env.GARDEN_ROOTFS_DRIVER) (list "map" "slice")}}{{.Values.env.GARDEN_ROOTFS_DRIVER | toJson | quote}}{{else}}{{.Values.env.GARDEN_ROOTFS_DRIVER | quote}}{{end}}{{else}}{{fail "env.GARDEN_ROOTFS_DRIVER has not been set"}}{{end}}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: {{if ne (typeOf .Values.env.KUBERNETES_CLUSTER_DOMAIN) "<nil>"}}{{if has (kindOf .Values.env.KUBERNETES_CLUSTER_DOMAIN) (list "map" "slice")}}{{.Values.env.KUBERNETES_CLUSTER_DOMAIN | toJson | quote}}{{else}}{{.Values.env.KUBERNETES_CLUSTER_DOMAIN | quote}}{{end}}{{else}}""{{end}}
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "PZ_LABEL_NAME"
          value: {{if ne (typeOf .Values.env.PZ_LABEL_NAME) "<nil>"}}{{if has (kindOf .Values.env.PZ_LABEL_NAME) (list "map" "slice")}}{{.Values.env.PZ_LABEL_NAME | toJson | quote}}{{else}}{{.Values.env.PZ_LABEL_NAME | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_HOST"
          value: {{if ne (typeOf .Values.env.SCF_LOG_HOST) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_HOST) (list "map" "slice")}}{{.Values.env.SCF_LOG_HOST | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_HOST | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_PORT"
          value: {{if ne (typeOf .Values.env.SCF_LOG_PORT) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_PORT) (list "map" "slice")}}{{.Values.env.SCF_LOG_PORT | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_PORT | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_PROTOCOL"
          value: {{if ne (typeOf .Values.env.SCF_LOG_PROTOCOL) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_PROTOCOL) (list "map" "slice")}}{{.Values.env.SCF_LOG_PROTOCOL | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_PROTOCOL | quote}}{{end}}{{else}}{{fail "env.SCF_LOG_PROTOCOL has not been set"}}{{end}}
        - name: "VCAP_HARD_NPROC"
          value: {{ .Values.kube.limits.nproc.hard | quote }}
        - name: "VCAP_SOFT_NPROC"
          value: {{ .Values.kube.limits.nproc.soft | quote }}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-autoscaler-postgres:4c8f1e04f39d028376a606a62ce120ab80076fe6"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-postgres"
        ports:
        - containerPort: 5432
          name: "postgres"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            {{- if and .Values.config.memory.requests .Values.sizing.autoscaler_postgres.memory.request }}
            memory: "{{ int .Values.sizing.autoscaler_postgres.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.config.cpu.requests .Values.sizing.autoscaler_postgres.cpu.request }}
            cpu: "{{ int .Values.sizing.autoscaler_postgres.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.config.memory.limits .Values.sizing.autoscaler_postgres.memory.limit }}
            memory: "{{ int .Values.sizing.autoscaler_postgres.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.config.cpu.limits .Values.sizing.autoscaler_postgres.cpu.limit }}
            cpu: "{{ int .Values.sizing.autoscaler_postgres.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.autoscaler_postgres.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.autoscaler_postgres.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.autoscaler_postgres.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

          allowPrivilegeEscalation: {{ if has "ALL" .Values.sizing.autoscaler_postgres.capabilities -}} true {{- else -}} false {{- end }}
        volumeMounts:
        - mountPath: "/var/vcap/store"
          name: "postgres-data"
          readOnly: false
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      {{- if ne .Values.kube.registry.username "" }}
      imagePullSecrets:
      - name: "registry-credentials"
      {{- end }}
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
  {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 7)) }}
  updateStrategy:
    type: "RollingUpdate"
  {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: "postgres-data"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "{{ .Values.sizing.autoscaler_postgres.disk_sizes.postgres_data }}G"
      storageClassName: {{ .Values.kube.storage_class.persistent | quote }}
