{{- if gt .Values.sizing.router.count 1.0 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: router
  namespace: {{ .Release.Namespace | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: "router"
{{- end }}
