---
{{- if ne .Values.kube.registry.username "" }}
apiVersion: "v1"
data:
  .dockercfg: {{ printf "{%q:{%q:%q,%q:%q,%q:%q}}" .Values.kube.registry.hostname "username" (default "" .Values.kube.registry.username) "password" (default "" .Values.kube.registry.password) "auth" (printf "%s:%s" .Values.kube.registry.username .Values.kube.registry.password | b64enc) | b64enc }}
kind: "Secret"
metadata:
  name: "registry-credentials"
  labels:
    app.kubernetes.io/component: "registry-credentials"
    skiff-role-name: "registry-credentials"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | quote }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") | quote }}
type: "kubernetes.io/dockercfg"
{{- end }}
