{{- $fullName := include "eirini-chart.fullname" . -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "eirini-chart.name" . }}
    release: {{ .Release.Name }}
spec:
  volumes:
    - name: config-volume
      configMap:
        name: {{ $fullName }}
        items:
        - key: opi.yaml
          path: opi.yml
        - key: kube.yaml
          path: kube.conf
  containers:
  - name: opi
    image: {{ .Values.config.opi_image }}
    volumeMounts:
    - name: config-volume
      mountPath: /workspace/jobs/opi/config
    ports:
      - containerPort: 8085
  - name: registry
    image: {{ .Values.config.registry_image }}
    ports:
      - containerPort: 8080
