---
# The diego-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - patch-properties: Dummy BOSH job used to host parameters that are used in
#   SCF patches for upstream bugs
#
# Also: bbs, cfdot, loggregator_agent
{{- if gt (int .Values.sizing.diego_api.count) 0 }}

{{- if gt (int .Values.sizing.diego_api.count) 3 }}
_maxReplicas: {{ fail "diego_api cannot have more than 3 instances" }}
{{- end }}

{{- if .Values.sizing.HA }}
_moved_sizing_HA: {{ fail "Bad use of moved variable sizing.HA. The new name to use is config.HA" }}
{{- end }}

{{- if .Values.sizing.cpu }}
_moved_sizing_cpu_limits: {{ if .Values.sizing.cpu.limits }} {{ fail "Bad use of moved variable sizing.cpu.limits. The new name to use is config.cpu.limits" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.cpu }}
_moved_sizing_cpu_requests: {{ if .Values.sizing.cpu.requests }} {{ fail "Bad use of moved variable sizing.cpu.requests. The new name to use is config.cpu.requests" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.memory }}
_moved_sizing_memory_limits: {{ if .Values.sizing.memory.limits }} {{ fail "Bad use of moved variable sizing.memory.limits. The new name to use is config.memory.limits" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.memory }}
_moved_sizing_memory_requests: {{ if .Values.sizing.memory.requests }} {{ fail "Bad use of moved variable sizing.memory.requests. The new name to use is config.memory.requests" }} {{else}} ok {{end}}
{{- end }}

apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "diego-api"
  labels:
    skiff-role-name: "diego-api"
spec:
  podManagementPolicy: "OrderedReady"
  replicas: {{ if .Values.env.ENABLE_OPI_STAGING -}} 0 {{- else -}} {{ .Values.sizing.diego_api.count }} {{- end }}
  serviceName: "diego-api-set"
  template:
    metadata:
      name: "diego-api"
      labels:
        skiff-role-name: "diego-api"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "diego-api"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
        {{- if .Values.sizing.diego_api.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.diego_api.affinity.nodeAffinity }}
        {{- end }}
      containers:
      - env:
        - name: "BBS_ACTIVE_KEY_PASSPHRASE"
          valueFrom:
            secretKeyRef:
              key: "bbs-active-key-passphrase"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"

        {{- if not .Values.secrets.BBS_AUCTIONEER_CERT }}
        - name: "BBS_AUCTIONEER_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_AUCTIONEER_CERT }}
        - name: "BBS_AUCTIONEER_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.BBS_AUCTIONEER_CERT_KEY }}
        - name: "BBS_AUCTIONEER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.BBS_AUCTIONEER_CERT_KEY }}
        - name: "BBS_AUCTIONEER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_REP_CERT }}
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.BBS_REP_CERT }}
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if not .Values.secrets.BBS_REP_CERT_KEY }}
        - name: "BBS_REP_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_REP_CERT_KEY }}
        - name: "BBS_REP_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert-key"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.BBS_SERVER_CRT }}
        - name: "BBS_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.BBS_SERVER_CRT }}
        - name: "BBS_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if not .Values.secrets.BBS_SERVER_CRT_KEY }}
        - name: "BBS_SERVER_CRT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.BBS_SERVER_CRT_KEY }}
        - name: "BBS_SERVER_CRT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt-key"
              name: "secrets"
        {{- end }}

        - name: "CATS_SUITES"
          value: {{if ne (typeOf .Values.env.CATS_SUITES) "<nil>"}}{{if has (kindOf .Values.env.CATS_SUITES) (list "map" "slice")}}{{.Values.env.CATS_SUITES | toJson | quote}}{{else}}{{.Values.env.CATS_SUITES | quote}}{{end}}{{else}}""{{end}}
        - name: "GARDEN_ROOTFS_DRIVER"
          value: {{if ne (typeOf .Values.env.GARDEN_ROOTFS_DRIVER) "<nil>"}}{{if has (kindOf .Values.env.GARDEN_ROOTFS_DRIVER) (list "map" "slice")}}{{.Values.env.GARDEN_ROOTFS_DRIVER | toJson | quote}}{{else}}{{.Values.env.GARDEN_ROOTFS_DRIVER | quote}}{{end}}{{else}}{{fail "env.GARDEN_ROOTFS_DRIVER has not been set"}}{{end}}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: {{if ne (typeOf .Values.env.KUBERNETES_CLUSTER_DOMAIN) "<nil>"}}{{if has (kindOf .Values.env.KUBERNETES_CLUSTER_DOMAIN) (list "map" "slice")}}{{.Values.env.KUBERNETES_CLUSTER_DOMAIN | toJson | quote}}{{else}}{{.Values.env.KUBERNETES_CLUSTER_DOMAIN | quote}}{{end}}{{else}}""{{end}}
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"

        {{- if .Values.secrets.LOGGREGATOR_AGENT_CERT }}
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.LOGGREGATOR_AGENT_CERT }}
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.LOGGREGATOR_AGENT_CERT_KEY }}
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.LOGGREGATOR_AGENT_CERT_KEY }}
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if not .Values.secrets.LOGGREGATOR_CLIENT_CERT }}
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.LOGGREGATOR_CLIENT_CERT }}
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.LOGGREGATOR_CLIENT_CERT_KEY }}
        - name: "LOGGREGATOR_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.LOGGREGATOR_CLIENT_CERT_KEY }}
        - name: "LOGGREGATOR_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert-key"
              name: "secrets"
        {{- end }}

        - name: "LOG_LEVEL"
          value: {{if ne (typeOf .Values.env.LOG_LEVEL) "<nil>"}}{{if has (kindOf .Values.env.LOG_LEVEL) (list "map" "slice")}}{{.Values.env.LOG_LEVEL | toJson | quote}}{{else}}{{.Values.env.LOG_LEVEL | quote}}{{end}}{{else}}{{fail "env.LOG_LEVEL has not been set"}}{{end}}

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.MYSQL_DIEGO_PASSWORD }}
        - name: "MYSQL_DIEGO_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.MYSQL_DIEGO_PASSWORD }}
        - name: "MYSQL_DIEGO_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "SCF_LOG_HOST"
          value: {{if ne (typeOf .Values.env.SCF_LOG_HOST) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_HOST) (list "map" "slice")}}{{.Values.env.SCF_LOG_HOST | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_HOST | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_PORT"
          value: {{if ne (typeOf .Values.env.SCF_LOG_PORT) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_PORT) (list "map" "slice")}}{{.Values.env.SCF_LOG_PORT | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_PORT | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_PROTOCOL"
          value: {{if ne (typeOf .Values.env.SCF_LOG_PROTOCOL) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_PROTOCOL) (list "map" "slice")}}{{.Values.env.SCF_LOG_PROTOCOL | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_PROTOCOL | quote}}{{end}}{{else}}{{fail "env.SCF_LOG_PROTOCOL has not been set"}}{{end}}
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-diego-api:f0f0a58963fd4eae22e187b2778511d51c349e43"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-api"
        ports:
        - containerPort: 8889
          name: "cell-bbs-api"
          protocol: "TCP"
        - containerPort: 17017
          name: "cell-bbs-dbg"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/usr/bin/env"
            - "FISSILE_ACTIVE_PASSIVE_PROBE=/var/vcap/jobs/global-properties/bin/readiness/diego-api"
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            {{- if and .Values.config.memory.requests .Values.sizing.diego_api.memory.request }}
            memory: "{{ int .Values.sizing.diego_api.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.config.cpu.requests .Values.sizing.diego_api.cpu.request }}
            cpu: "{{ int .Values.sizing.diego_api.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.config.memory.limits .Values.sizing.diego_api.memory.limit }}
            memory: "{{ int .Values.sizing.diego_api.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.config.cpu.limits .Values.sizing.diego_api.cpu.limit }}
            cpu: "{{ int .Values.sizing.diego_api.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.diego_api.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.diego_api.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.diego_api.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
  {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 7)) }}
  updateStrategy:
    type: "RollingUpdate"
  {{- end }}
{{- end }}
---
{{- if gt (int .Values.sizing.diego_api.count) 0 }}
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "cell-bbs-api"
      port: 8889
      protocol: "TCP"
      targetPort: 0
    - name: "cell-bbs-dbg"
      port: 17017
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "diego-api"
      skiff-role-active: "true"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-api-bbs-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "cell-bbs-api"
      port: 8889
      protocol: "TCP"
      targetPort: 0
    - name: "cell-bbs-dbg"
      port: 17017
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "diego-api"
      skiff-role-active: "true"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-api-bbs"
  spec:
    ports:
    - name: "cell-bbs-api"
      port: 8889
      protocol: "TCP"
      targetPort: 8889
    - name: "cell-bbs-dbg"
      port: 17017
      protocol: "TCP"
      targetPort: 17017
    selector:
      skiff-role-name: "diego-api"
      skiff-role-active: "true"
kind: "List"
{{- end }}
