---
# The log-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - route_registrar: Used for registering routes
#
# Also: loggregator_trafficcontroller, loggregator_agent, reverse_log_proxy

{{- if gt (int .Values.sizing.log_api.count) 65535 }}
_maxReplicas: {{ fail "log_api cannot have more than 65535 instances" }}
{{- end }}

{{- if and .Values.config.HA (and (ne (int .Values.sizing.log_api.count) 1) (lt (int .Values.sizing.log_api.count) 2)) }}
_minHAReplicas: {{ fail "log_api must have at least 2 instances for HA" }}
{{- end }}

{{- if lt (int .Values.sizing.log_api.count) 1 }}
_minReplicas: {{ fail "log_api must have at least 1 instances" }}
{{- end }}

{{- if .Values.sizing.HA }}
_moved_sizing_HA: {{ fail "Bad use of moved variable sizing.HA. The new name to use is config.HA" }}
{{- end }}

{{- if .Values.sizing.cpu }}
_moved_sizing_cpu_limits: {{ if .Values.sizing.cpu.limits }} {{ fail "Bad use of moved variable sizing.cpu.limits. The new name to use is config.cpu.limits" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.cpu }}
_moved_sizing_cpu_requests: {{ if .Values.sizing.cpu.requests }} {{ fail "Bad use of moved variable sizing.cpu.requests. The new name to use is config.cpu.requests" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.memory }}
_moved_sizing_memory_limits: {{ if .Values.sizing.memory.limits }} {{ fail "Bad use of moved variable sizing.memory.limits. The new name to use is config.memory.limits" }} {{else}} ok {{end}}
{{- end }}

{{- if .Values.sizing.memory }}
_moved_sizing_memory_requests: {{ if .Values.sizing.memory.requests }} {{ fail "Bad use of moved variable sizing.memory.requests. The new name to use is config.memory.requests" }} {{else}} ok {{end}}
{{- end }}

apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "log-api"
  labels:
    skiff-role-name: "log-api"
spec:
  podManagementPolicy: "Parallel"
  replicas: {{ if and .Values.config.HA (eq (int .Values.sizing.log_api.count) 1) -}} 2 {{- else -}} {{ .Values.sizing.log_api.count }} {{- end }}
  serviceName: "log-api-set"
  template:
    metadata:
      name: "log-api"
      labels:
        skiff-role-name: "log-api"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "skiff-role-name"
                  operator: "In"
                  values:
                  - "log-api"
              topologyKey: "beta.kubernetes.io/os"
            weight: 100
        {{- if .Values.sizing.log_api.affinity.nodeAffinity }}
        nodeAffinity: {{ toJson .Values.sizing.log_api.affinity.nodeAffinity }}
        {{- end }}
      containers:
      - env:
        - name: "CATS_SUITES"
          value: {{if ne (typeOf .Values.env.CATS_SUITES) "<nil>"}}{{if has (kindOf .Values.env.CATS_SUITES) (list "map" "slice")}}{{.Values.env.CATS_SUITES | toJson | quote}}{{else}}{{.Values.env.CATS_SUITES | quote}}{{end}}{{else}}""{{end}}
        - name: "DOMAIN"
          value: {{if ne (typeOf .Values.env.DOMAIN) "<nil>"}}{{if has (kindOf .Values.env.DOMAIN) (list "map" "slice")}}{{.Values.env.DOMAIN | toJson | quote}}{{else}}{{.Values.env.DOMAIN | quote}}{{end}}{{else}}{{fail "env.DOMAIN has not been set"}}{{end}}
        - name: "GARDEN_ROOTFS_DRIVER"
          value: {{if ne (typeOf .Values.env.GARDEN_ROOTFS_DRIVER) "<nil>"}}{{if has (kindOf .Values.env.GARDEN_ROOTFS_DRIVER) (list "map" "slice")}}{{.Values.env.GARDEN_ROOTFS_DRIVER | toJson | quote}}{{else}}{{.Values.env.GARDEN_ROOTFS_DRIVER | quote}}{{end}}{{else}}{{fail "env.GARDEN_ROOTFS_DRIVER has not been set"}}{{end}}

        {{- if not .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.INTERNAL_CA_CERT }}
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        {{- end }}

        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: {{if ne (typeOf .Values.env.KUBERNETES_CLUSTER_DOMAIN) "<nil>"}}{{if has (kindOf .Values.env.KUBERNETES_CLUSTER_DOMAIN) (list "map" "slice")}}{{.Values.env.KUBERNETES_CLUSTER_DOMAIN | toJson | quote}}{{else}}{{.Values.env.KUBERNETES_CLUSTER_DOMAIN | quote}}{{end}}{{else}}""{{end}}
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: {{ .Values.sizing.nats.count | quote }}

        {{- if not .Values.secrets.LOGGREGATOR_AGENT_CERT }}
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.LOGGREGATOR_AGENT_CERT }}
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.LOGGREGATOR_AGENT_CERT_KEY }}
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.LOGGREGATOR_AGENT_CERT_KEY }}
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if not .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.MONIT_PASSWORD }}
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.NATS_PASSWORD }}
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.NATS_PASSWORD }}
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        {{- end }}

        - name: "SCF_LOG_HOST"
          value: {{if ne (typeOf .Values.env.SCF_LOG_HOST) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_HOST) (list "map" "slice")}}{{.Values.env.SCF_LOG_HOST | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_HOST | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_PORT"
          value: {{if ne (typeOf .Values.env.SCF_LOG_PORT) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_PORT) (list "map" "slice")}}{{.Values.env.SCF_LOG_PORT | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_PORT | quote}}{{end}}{{else}}""{{end}}
        - name: "SCF_LOG_PROTOCOL"
          value: {{if ne (typeOf .Values.env.SCF_LOG_PROTOCOL) "<nil>"}}{{if has (kindOf .Values.env.SCF_LOG_PROTOCOL) (list "map" "slice")}}{{.Values.env.SCF_LOG_PROTOCOL | toJson | quote}}{{else}}{{.Values.env.SCF_LOG_PROTOCOL | quote}}{{end}}{{else}}{{fail "env.SCF_LOG_PROTOCOL has not been set"}}{{end}}

        {{- if not .Values.secrets.SYSLOG_RLP_CERT }}
        - name: "SYSLOG_RLP_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.SYSLOG_RLP_CERT }}
        - name: "SYSLOG_RLP_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.SYSLOG_RLP_CERT_KEY }}
        - name: "SYSLOG_RLP_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.SYSLOG_RLP_CERT_KEY }}
        - name: "SYSLOG_RLP_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if not .Values.secrets.TRAFFICCONTROLLER_CERT }}
        - name: "TRAFFICCONTROLLER_CERT"
          valueFrom:
            secretKeyRef:
              key: "trafficcontroller-cert"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.TRAFFICCONTROLLER_CERT }}
        - name: "TRAFFICCONTROLLER_CERT"
          valueFrom:
            secretKeyRef:
              key: "trafficcontroller-cert"
              name: "secrets"
        {{- end }}

        {{- if .Values.secrets.TRAFFICCONTROLLER_CERT_KEY }}
        - name: "TRAFFICCONTROLLER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "trafficcontroller-cert-key"
              name: "secrets"
        {{- end }}

        {{- if not .Values.secrets.TRAFFICCONTROLLER_CERT_KEY }}
        - name: "TRAFFICCONTROLLER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "trafficcontroller-cert-key"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"

        {{- if not .Values.secrets.UAA_CLIENTS_DOPPLER_SECRET }}
        - name: "UAA_CLIENTS_DOPPLER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-doppler-secret"
              name: "secrets-{{ .Chart.Version }}-{{ .Values.kube.secrets_generation_counter }}"
        {{- end }}

        {{- if .Values.secrets.UAA_CLIENTS_DOPPLER_SECRET }}
        - name: "UAA_CLIENTS_DOPPLER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-doppler-secret"
              name: "secrets"
        {{- end }}

        - name: "UAA_HOST"
          value: {{if ne (typeOf .Values.env.UAA_HOST) "<nil>"}}{{if has (kindOf .Values.env.UAA_HOST) (list "map" "slice")}}{{.Values.env.UAA_HOST | toJson | quote}}{{else}}{{.Values.env.UAA_HOST | quote}}{{end}}{{else}}{{fail "env.UAA_HOST has not been set"}}{{end}}
        - name: "UAA_PORT"
          value: {{if ne (typeOf .Values.env.UAA_PORT) "<nil>"}}{{if has (kindOf .Values.env.UAA_PORT) (list "map" "slice")}}{{.Values.env.UAA_PORT | toJson | quote}}{{else}}{{.Values.env.UAA_PORT | quote}}{{end}}{{else}}""{{end}}
        image: "{{ .Values.kube.registry.hostname }}/{{ .Values.kube.organization }}/scf-log-api:bdb74026b48e005353c5a6cabaf7a42f6c264aea"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "log-api"
        ports:
        - containerPort: 8081
          name: "dropsonde"
          protocol: "TCP"
        - containerPort: 8082
          name: "rlp"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8081/set-cookie"
        resources:
          requests:
            {{- if and .Values.config.memory.requests .Values.sizing.log_api.memory.request }}
            memory: "{{ int .Values.sizing.log_api.memory.request }}Mi"
            {{- end }}

            {{- if and .Values.config.cpu.requests .Values.sizing.log_api.cpu.request }}
            cpu: "{{ int .Values.sizing.log_api.cpu.request }}m"
            {{- end }}

          limits:
            {{- if and .Values.config.memory.limits .Values.sizing.log_api.memory.limit }}
            memory: "{{ int .Values.sizing.log_api.memory.limit }}Mi"
            {{- end }}

            {{- if and .Values.config.cpu.limits .Values.sizing.log_api.cpu.limit }}
            cpu: "{{ int .Values.sizing.log_api.cpu.limit }}m"
            {{- end }}

        securityContext:
          {{- if has "ALL" .Values.sizing.log_api.capabilities }}
          privileged: true
          {{- end }}

          {{- if not (has "ALL" .Values.sizing.log_api.capabilities) }}
          capabilities:
            add:
            {{- range .Values.sizing.log_api.capabilities }}
            - {{ . | upper }}
            {{- end }}
          {{- end }}

        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
  {{- if or (gt (int .Capabilities.KubeVersion.Major) 1) (and (eq (int .Capabilities.KubeVersion.Major) 1) (ge (.Capabilities.KubeVersion.Minor | trimSuffix "+" | int) 7)) }}
  updateStrategy:
    type: "RollingUpdate"
  {{- end }}
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "dropsonde"
      port: 8081
      protocol: "TCP"
      targetPort: 0
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-loggregator-trafficcontroller-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "dropsonde"
      port: 8081
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-loggregator-trafficcontroller"
  spec:
    ports:
    - name: "dropsonde"
      port: 8081
      protocol: "TCP"
      targetPort: 8081
    selector:
      skiff-role-name: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-reverse-log-proxy-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-reverse-log-proxy"
  spec:
    ports:
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: 8082
    selector:
      skiff-role-name: "log-api"
kind: "List"
